[package]
name = "billing"
version = "0.1.0"

[lib]
name = "billing_lib"
path = "src/lib.rs"

[dependencies]
config = "0.7"
log = "0.4"
derive_more = "0.11"
env_logger = "0.5.6"
hyper = "0.11"
futures = "0.1.17"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.3.2", features = ["postgres", "extras"] }
r2d2 = "0.8.1"
r2d2-diesel = "1.0.0"
validator = "0.6.3"
validator_derive = "0.6.1"
tokio-core = "0.1"
futures-cpupool = "0.1.7"
hyper-tls="0.1.3"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
failure = "0.1.1"
stq_http = { path = "vendor/libstqbackend/http" }
stq_router = { path = "vendor/libstqbackend/router" }
stq_static_resources = { path = "vendor/libstqbackend/static_resources" }
uuid = { version = "*", features = ["use_std", "v4", "serde"] }
