[saga_addr]
url = "http://saga:8000"

[stores_microservice]
url="http://stores:8000"

[callback]
url = "http://billing:8000"

# [payments]
# url = "https://pay-nightly.stq.cloud"
# jwt_public_key_base64 = ""
# user_jwt = ""
# user_private_key = ""
# device_id = ""
# min_pooled_accounts = 10
# sign_public_key = ""

# [payments.accounts]
# main_stq = "f90d449f-a066-412e-835d-aca28d80d043"
# main_eth = "5ec22029-0410-44f1-9e29-57eecf467349"
# main_btc = "64eebbcd-db65-486a-a83a-7cdd631ef1c1"
# cashback_stq = "a22ece2f-e7bf-4a24-a338-2f60dab777bf"

[external_billing]
invoice_url = "http://payments.tugush.com/api/v1/invoices/"
login_url = "http://payments.tugush.com/api/v1/login/"
username = "storiqa"
password = "DuRZx,E}8&myT^%-"
amount_recalculate_timeout_sec = 600

[graylog]
addr = "udplog.stq.cloud:32303"

[stripe]
public_key = "pk_test_hH0fg7QCeCIE7ZmVN19h6l9C"
secret_key = "sk_test_NZtkQf1xKGjkreVbKddipafS"
signing_secret = "whsec_JUD38zIxOWtFEJYgBucio65J4xoZ057O"

[event_store]
max_processing_attempts = 1
stuck_threshold_sec = 60
polling_rate_sec = 5

[fee]
order_percent = 5
currency_code = "eur"

[payment_expiry]
crypto_timeout_min = 1
fiat_timeout_min = 1
