[saga_addr]
url = "http://saga:8000"

[callback]
url = "http://billing:8000"

[external_billing]
invoice_url = "http://payments.tugush.com/api/v1/invoices/"
merchant_url = "http://payments.tugush.com/api/v1/merchants/"
login_url = "http://payments.tugush.com/api/v1/login/"
username = "storiqa"
password = "DuRZx,E}8&myT^%-"
amount_recalculate_timeout_sec = 600

[graylog]
addr = "udplog.stq.cloud:32303"

[stripe]
api_key = ""
