[jwt]
secret_key_path = "config/keys/private_key.der"
check_email = false

[google]
info_url = "https://www.googleapis.com/userinfo/v2/me"

[facebook]
info_url = "https://graph.facebook.com/me"

[saga_addr]
url = "http://saga:8004"

[notifications]
url = "http://notifications:8005"
verify_email_path = "https://localhost/verify_email"
reset_password_path = "https://localhost/password_reset"
